export default {
  "$background-color-primary": "#409eff",
  "$background-color-success": "#67c23a",
  "$background-color-warning": "#e6a23c",
  "$background-color-danger": "#f56c6c",
  "$background-color-info": "#909399",
  "$color-white": "#fff",
  "$color-black": "#000",
  "$color-primary": "#409eff",
  "$color-success": "#67c23a",
  "$color-warning": "#e6a23c",
  "$color-danger": "#f56c6c",
  "$color-info": "#909399",
  "$text-color-primary": "#303133",
  "$text-color-regular": "#606266",
  "$text-color-secondary": "#909399",
  "$text-color-placeholder": "#c0c4cc",
// main
  "$main-body-background-color": "#f5f5f5",
  "$main-content-bockground-color": "#f5f5f5",
// header
  "$header-color": "$color-white",
  "$header-background-color": "#324148",
  "$header-border-color": "#4b5960",
// sidebar
  "$sidebar-background-color": "#263238",
  "$sidebar-user-profile-color": "$color-white",
// menu
  "$menu-background-color": "#263238",
  "$menu-submenu-border-color": "#4b5960",
  "$menu-item-color": "#d1d1d1",
  "$menu-item-first-level-active-background-color": "#29b0a3",
  "$menu-item-second-level-active-background-color": "#182125",
  "$menu-item-submenu-second-level-hover-background-color": "#1e282d",
  "$menu-item-active-color": "$color-white",
// breadcrumb
  "$breadcrumb-background-color": "$color-white",
  "$breadcrumb-border-color": "#ddd",
// footer
  "$footer-color": "#37474f",
// card
  "$card-border-color": "#ddd",
// list
  "$list-border-color": "#ddd",
// separator
  "$separator-border-color": "#ddd",
// table
  "$table-border-color": "#ddd",
  "$table-head-background-color": "$color-white",
  "$table-head-separator-border-color": "#bbb",
  "$table-column-striped-background-color": "#faf5f5",
// login
  "$login-body-box-shadow": "#ddd",
  "$login-body-border-color": "#ddd",
  "$login-body-background-color": "$color-white",
  "$login-body-submit-background-color": "#516671",
  "$login-body-submit-color": "$color-white",
// edit
  "$edit-fields-item-readonly-background-color": "#f2f2f2",
  "$edit-fields-item-readonly-color": "#999",
  "$edit-fields-item-border-color": "#ddd",
}
